#サーバー設定
server:
  port: 8080
  servlet:
    context-path: /task_manager

#DB接続設定
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    
mybatis:
  mapper-locations: classpath:/com/task_manager/mapper/*.xml
  type-aliases-package: com.task_manager.entity